//
//  CnnEmotionsModel.swift
//  Awesome ML
//
//  Created by Eugene Bokhan on 4/3/18.
//  Copyright © 2018 Eugene Bokhan. All rights reserved.
//

import Foundation

public let cnnEmotionsModel = CoreMLModel(name: "CNNEmotions", coreMLType: .cnnEmotions, shortDescription: "Emotion Recognition in the Wild via Convolutional Neural Networks and Mapped Binary Patterns", detailedDescription: "# Authors and Contributors \n Gil Levi and Tal Hassner, Emotion Recognition in the Wild via Convolutional Neural Networks and Mapped Binary Patterns, Proc. ACM International Conference on Multimodal Interaction (ICMI), Seattle, Nov. 2015 \n # Abstract \n We present a novel method for classifying emotions from static facial images. Our approach leverages on the recent success of Convolutional Neural Networks (CNN) on face recognition problems. Unlike the settings often assumed there, far less labeled data is typically available for training emotion classi cation systems. Our method is therefore designed with the goal of simplifying the problem domain by removing confounding factors from the input images, with an emphasis on image illumination variations. This, in an effort to reduce the amount of data required to e ectively train deep CNN models. To this end, we propose novel transformations of image intensities to 3D spaces, designed to be invariant to monotonic photometric transformations. These are applied to CASIA Webface images which are then used to train an ensemble of multiple architecture CNNs on multiple representations. Each model is then ne-tuned with limited emotion labeled training data to obtain nal classi cation models. Our method was tested on the Emotion Recognition in the Wild Challenge (EmotiW 2015), Static Facial Expression Recognition sub-challenge (SFEW) and shown to provide a substantial, 15.36% improvement over baseline results (40% gain in performance). \n ## Input  \n A color (227x227) image. \n ## Output \n The most likely age, for the given input. \n ## License \n Public Domain", image: #imageLiteral(resourceName: "CNNEmotions Cover"), inputWidth: 224, inputHeight: 224, remoteURL: URL(string: "https://s3-us-west-2.amazonaws.com/coreml-models/CNNEmotions.mlmodel")!, remoteZipURL: URL(string: "https://drive.google.com/uc?export=download&id=1ZbAt9NQf18SJ9PYx2S7lOQ0dsGtbwQLv")!, license: "MIT")
